apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-techdocs
  description: An example of a Backstage application.
  backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
